# Generated by Django 3.2.4 on 2021-06-06 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onibus',
            fields=[
                ('placa', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('estaLotado', models.BooleanField()),
                ('dtAlteracao', models.DateTimeField(auto_now_add=True)),
                ('qtnPassageirosAtual', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('sentidoIda', models.CharField(max_length=255)),
                ('sentidoVolta', models.CharField(max_length=255)),
                ('identificacao', models.CharField(max_length=10)),
                ('limite', models.IntegerField()),
            ],
        ),
    ]
